//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kosarka_ITivity_Dejan_Savanovic.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igrac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Igrac()
        {
            this.UcinakIgracas = new HashSet<UcinakIgraca>();
        }
    
        public int IgracID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string Drzava { get; set; }
        public int GradID { get; set; }
        public int TimID { get; set; }
        public int PozicijaID { get; set; }
        public Nullable<int> SlikaID { get; set; }
        public byte BrojDresa { get; set; }
    
        public virtual Grad Grad { get; set; }
        public virtual Pozicija Pozicija { get; set; }
        public virtual Slika Slika { get; set; }
        public virtual Tim Tim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcinakIgraca> UcinakIgracas { get; set; }
    }
}
