//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kosarka_ITivity_Dejan_Savanovic.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kolo()
        {
            this.Utakmicas = new HashSet<Utakmica>();
        }
    
        public int KoloID { get; set; }
        public int BrojKola { get; set; }
        public System.DateTime DatumPocetkaKola { get; set; }
        public System.DateTime DatumKrajKola { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utakmica> Utakmicas { get; set; }
    }
}
