//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kosarka_ITivity_Dejan_Savanovic.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KosarkaContext : DbContext
    {
        public KosarkaContext()
            : base("name=KosarkaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grad> Grads { get; set; }
        public virtual DbSet<Igrac> Igracs { get; set; }
        public virtual DbSet<Kolo> Koloes { get; set; }
        public virtual DbSet<Pozicija> Pozicijas { get; set; }
        public virtual DbSet<Slika> Slikas { get; set; }
        public virtual DbSet<Tim> Tims { get; set; }
        public virtual DbSet<UcinakIgraca> UcinakIgracas { get; set; }
        public virtual DbSet<Utakmica> Utakmicas { get; set; }
    }
}
